dist: xenial
language: crystal
services:
  - redis-server
crystal:
  - latest
  - nightly
matrix:
  allow_failures:
    - crystal: nightly
env:
  - STORE=memory
  - STORE=redis
script:
  - bin/ameba
  - crystal spec --verbose
