name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        store: ["memory", "redis"]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Cache shards
        uses: actions/cache@v2
        with:
          path: ~/.cache/shards
          key: shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-

      - name: Install shards
        run: shards update

      - name: Run tests
        run: crystal spec
        env:
          STORE: ${{ matrix.store }}
